name: 'Todo Issues'
author: 'Villiam Riegler, ...'
inputs:
  # Context variables about the workflow https://docs.github.com/en/actions/learn-github-actions/contexts
  # Inputs are set as environment variables 
  REPO:
    desecription: 'Path to github repository'
    required: false
    default: '${{github.repository}}'
  TOKEN: 
    desecription: 'Authentication token to allow issue creation'
    required: false
  API_URL:
    desecription: 'Base url of github api'
    required: false
    default: '${{github.api_url}}'
  
runs: 
  using: 'docker'
  image: 'ghcr.io/indaplus22/villiamr-karpov-project:sha256-afd2f1f5975cc752d977ae5edab7ba8d1887e7a57f52f54508e6733749ed65be.sig'

