mod api_interaction;
use reqwest::Error;

#[tokio::main]
async fn main() -> Result<(), Error>{    
    let api = api_interaction::GithubApiClient::new();
    //api.post_issue("First issue".to_string(), "Generated by action if successfull".to_string()).await?;
    api.get_files().await?;
    Ok(())
}
