name: Integration test

on:
  #pull_request:
  #  branches: [main]
  workflow_run:
    workflows: ['Docker']
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    
jobs:
  run-container: # Simply runs the program 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
  context_dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
# More tests to be added ...
